### ISSUE TITLE
Add build hashes to the title bar

### ISSUE THREAD

**Issue by literalmente-game** [JaCzekanski/Avocado#10]
An easy way for users to identify the build they're using is to show the build hash on the title bar.
So, the new title bar would look like:
* "Avocado: build 0abcde12 - FPS: 59 (17.00 ms)"

**Comment by JaCzekanski** [comment]
Done

![2018-03-07_21h08_04](https://user-images.githubusercontent.com/3662990/37115541-af070e16-224b-11e8-82a9-13cd97ce2e30.png)

**Comment by literalmente-game** [comment]
Ninja'ed me to it, was about to post the screenshot haha
