### ISSUE TITLE
Support DualShock controller emulation

### ISSUE THREAD

**Issue by literalmente-game** [JaCzekanski/Avocado#11]
Some games are compatible with DualShock controllers that are not supported/emulated now by Avocado. Ape Escape cannot be played because the game explicitly requires DualShock to start up (game hangs before the menu as the support is not yet implemented.

Detailed information about the DualShock: https://en.m.wikipedia.org/wiki/DualShock

**Comment by Invictaz** [comment]
And of you connect a Dualshock via an USB adapter?

**Comment by JaCzekanski** [comment]
Added support in d3a42c9
