### ISSUE TITLE
cpuVramToVram: Suspicious arg0

### ISSUE THREAD

**Issue by Snicks321** [JaCzekanski/Avocado#24]
* Build: 04/07/2018 (https://github.com/JaCzekanski/Avocado/commit/14d79778bbeef3ca6092a992b8c8b11159d48c6f)
* OS: Windows 7 64-Bits
* Bios: SCPH1001
* Hardware: CPU: I3 7100, GPU: NVidia 1050, RAM: 8GB.
* Game: Digimon Rumble Arena (U) - SLUS-01404
* Behavior: I was playing, everything was just fine, but then, for no reason, grapichs start to fail, then console logs, I can play, but with grapich errors.
* Screenshots/Videos: ![image](https://user-images.githubusercontent.com/12128168/42313974-596959f0-801a-11e8-880e-732e1be9dac8.png)
* Log: [logs-(SLUS-01404).txt](https://github.com/JaCzekanski/Avocado/files/2165853/logs-.SLUS-01404.txt)

EDIT: now grapichs looks even worse, and have more logs (I assume that is all from the same error, something is wrong copying to Vram and it start rendering something else, for example, one sprite from another character was showing on a battle)

cpuVramToVram: Suspicious arg0: 0x1e4fc0
cpuVramToVram: Suspicious arg0: 0x1e47c0
cpuVramToVram: Suspicious arg0: 0x1047d0
cpuVramToVram: Suspicious arg0: 0x104fc0

**Comment by JaCzekanski** [comment]
It would be helpful to know if there was such log in console:
```GPU DMA transfer too long, breaking.```
before "Suspicious arg0" warnings.

In future please attach full log - it's easier to find culprit when looking at whole file.




_note: possible GPU implementation bug or DMA issue._

**Comment by Snicks321** [comment]
No, there wasn't any log on console, or atleast no one I could see, it was only that error, nothing else. But can't be 100% sure now, because I did a fast copy paste from console logs, and close.

**Comment by JaCzekanski** [comment]
Should now be fixed in a0505bcddfd7a7e1df31d7b658e8776b152ebae2
