### ISSUE TITLE
40 Winks (U) hangs when loading

### ISSUE THREAD

**Issue by literalmente-game** [JaCzekanski/Avocado#37]
* Build: 5153b9
* OS: Windows 7
* Hardware: i3 2100, GTX 1050 TI, 4GB RAM DDR3
* Game: 40 Winks (U). ID: SLUS-00874
* Behavior: Avocado hangs when trying to load the game
* Log: [log.txt](https://github.com/JaCzekanski/Avocado/files/2625918/log.txt)

**Comment by JaCzekanski** [comment]
Game boots with Digital controller only - Analog will prevent it from reaching intro/menu.

**Comment by JaCzekanski** [comment]
Analog controller issue fixed in 22a451fbacd7704d13461ae7f4ea602e915cedf9
