### ISSUE TITLE
Bust-A-Move 2: arrow position issue

### ISSUE THREAD

**Issue by leirn** [JaCzekanski/Avocado#44]
* Build: 20/12/2018
* OS: Windows 10 b1809
* Hardware: Intel i7-4720, GTX965M, RAM 8GB.
* Game: Bust-A-Move 2: Arcade Edition , SLES-00278
* Behavior: The arrow to aim the shots shifts position when not vertical
* Screenshots/Videos: 
![vertical](https://user-images.githubusercontent.com/5393005/50576085-62b4f900-0e0a-11e9-89e4-5ed458c72d3f.png)

![shifted](https://user-images.githubusercontent.com/5393005/50576084-62b4f900-0e0a-11e9-9c7e-50aa37a72dfa.png)

**Comment by leirn** [comment]
I don't know if it can be relevant, but for the report it happens with both software and hardware graphics.

**Comment by JaCzekanski** [comment]
@leirn Thanks for the submission. 
Info about software and hardware rendering is in fact a valuable information.

My first guess would be bug in GTE implementation, but I need to check it.

Sorry for the delay, GitHub wasn't sending me issue notifications :(

**Comment by leirn** [comment]
No problem. Let me know if you need anything: testing, logs, correction validation, files of any sort...

**Comment by JaCzekanski** [comment]
I'm working on fixing the implementation of GTE module in #4, I'm hoping it'll resolve this issue.

**Comment by leirn** [comment]
Ok, let me know if and when you need some testing.

**Comment by JaCzekanski** [comment]
@leirn There was an update related to this issue. Could you test this game once more using the latest version?

**Comment by leirn** [comment]
It works with build develop-a88c7b  x64 from 2019-01-13 at 12:22:51

Thanks !
