### ISSUE TITLE
Alpine linux error imgui

### ISSUE THREAD

**Issue by sodomon2** [JaCzekanski/Avocado#53]
I have a mistake in compiling with imgui Here's the mistake. 

imgui.cpp
In file included from ../../../externals/imgui/imgui.cpp:977:
../../../externals/imgui/imgui.h:1205:56: error: 'operator new' takes type 'size_t' ('unsigned int') as first parameter [-fpermissive]
 inline void* operator new(size_t, ImNewDummy, void* ptr) { return ptr; }
                                                        ^
make[1]: *** [Makefile:187: obj/x86/debug/imgui.o] Error 1
make: *** [Makefile:89: imgui] Error 2

**Comment by JaCzekanski** [comment]
Hello
I need more info about your build environment to reproduce this issue:
- System version and processor architecture (x86/x64, other?)
- Compilator type and version (gcc/clang)
- What build commands are you using (`make config=release_x64 avocado`, something different).

**Comment by sodomon2** [comment]
* System version and processor architecture (x86/x64, other?)
    Alpine linux x86_64
 
* Compilator type and version (gcc/clang)
   gcc

Well apparently I already found the bug was that it detected the x86 architecture and I have x86_64

and apparently passing this command
  * make config=release_x64 avocado
the architecture changes to x86_64 
but it gives me another mistake

And here's the mistake.
==== Building core (release_x64) ====
voice.cpp
../../../src/device/spu/voice.cpp: In member function 'void spu::Voice::processEnvelope()':
../../../src/device/spu/voice.cpp:64:69: error: 'ceil' is not a member of 'std'
             step = static_cast<int>(static_cast<float>(step) * std::ceil(static_cast<float>(adsrVolume._reg) / static_cast<float>(0x8000)));
                                                                     ^~~~
../../../src/device/spu/voice.cpp:64:69: note: suggested alternative: 'cend'
             step = static_cast<int>(static_cast<float>(step) * std::ceil(static_cast<float>(adsrVolume._reg) / static_cast<float>(0x8000)));
                                                                     ^~~~
                                                                     cend
make[1]: *** [Makefile:360: obj/x64/release/voice.o] Error 1
make: *** [Makefile:107: core] Error 2
make: *** Waiting for unfinished jobs....

**Comment by JaCzekanski** [comment]
Please try building latest commit e106b75, there were few issues in code that prevented it from building on certain compilers.

In case of merge conflicts, reset branch to origin (I was rebasing the code):
```
git fetch
git reset --hard origin/develop
```

**Comment by sodomon2** [comment]
apparently I cloned the code again and compile with these instructions

* premake5 gmake
* make config=release_x64 avocado

and I compile without errors but at the time of running the emulator says to me 

Illegal instruction

**Comment by JaCzekanski** [comment]
It seems like you have older cpu which doesn't support AVX. You have to either build 32 bit version or remove this line from premake5.lua and rebuild the whole project (as 64 bit version) 
`vectorextensions "AVX"`

**Comment by sodomon2** [comment]
Thank you very much but now that I did it gives me another error here the error

[GL] Cannot load render shader: File doesn't exists.
Cannot setup graphics

**Comment by JaCzekanski** [comment]
Oops, I forgot to fix that. It will be fixed in future commits. 

Simply comment line 
`chdir(workingDirectory.c_str());`
in src/platform/windows/main.cpp
