### ISSUE TITLE
typical mistakes and shortcomings

### ISSUE THREAD

**Issue by shikulja** [JaCzekanski/Avocado#54]
W10 x64
http://www.emucr.com/2019/08/avocado-git-20190826.html

7700k z270 32gb (intel 630 with last drivers)
in all games
screen flickers in hardware mode

video:
https://mega.nz/#!RMBEFaLY!YJiBoculeqcPo_gOCQ7DwzNUG7wH4f9CP0TF_YKgknI
![avocado 2019-08-26 18-57-00-982](https://user-images.githubusercontent.com/3386359/63705387-aa730f80-c835-11e9-932b-13408e72618c.jpg)

- as always, directories with cyrillic are not defined. When you select an image from such a directory, the emulator closes.
![avocado 2019-08-26 19-10-21-164](https://user-images.githubusercontent.com/3386359/63705516-fde55d80-c835-11e9-9ab0-ba5273740db3.jpg)

- still the early stage of the emulator, I decided not to add it to a separate topic, I will express it as a wish.
Add high-quality vibration
even in pcsx2 with a ps3 gamepad .. the vibration is just disgusting. for example, the effects of the transition from soft to rough vibration were not felt,
(for example, the heartbeat and breath of the hero) I was very surprised how cool it is on the original console. And although psx (one) has less advanced vibration, I hope that it will be closest to the original.

- alt + enter full screen mode
- savestate support is relevant for detecting game bugs in the early stages

**Comment by JaCzekanski** [comment]
> screen flickers in hardware mode

Hardware mode is currently lagging behind software in terms of capabilities and compatibility. Will be fixed (someday).

> as always, directories with cyrillic are not defined

I can confirm that file browser crashes with Unicode characters. Moved to #55 .

> Add high-quality vibration

I haven't investigated vibration support yet. If SDL haptic subsystem allows for such precise vibration control, I'll consider adding it #27 

> alt + enter full screen mode

Added

> savestate support is relevant for detecting game bugs in the early stages

Savestate support was omitted on purpose - the architecture of emulator is not stable and some parts may change over time which would break compatibility between builds.
I created a separate issue for it #56 



Thanks for your feedback. 🤟
