### ISSUE TITLE
not open app on android

### ISSUE THREAD

**Issue by hermanG1994** [JaCzekanski/Avocado#62]
avocado stopped

my specs:
HTC U11 Life Android 8.0
sdm630

**Comment by hermanG1994** [comment]
I'll try a previous build.

edit.
the previous build is working for me

**Comment by JaCzekanski** [comment]
Can confirm - happens on my phone too. Crash is most likely related to the last ImGUI dependency update.
Will be fixed in future commits.

**Comment by hermanG1994** [comment]
> 
> 
> Can confirm - happens on my phone too. Crash is most likely related to the last ImGUI dependency update.
> Will be fixed in future commits.

if in the last build does not open the app
![imagen](https://user-images.githubusercontent.com/52355248/64911033-de31ae80-d6ea-11e9-9c02-de356cd90a46.png)

**Comment by hermanG1994** [comment]
> 
> 
> > Can confirm - happens on my phone too. Crash is most likely related to the last ImGUI dependency update.
> > Will be fixed in future commits.
> 
> if in the last build does not open the app
> ![imagen](https://user-images.githubusercontent.com/52355248/64911033-de31ae80-d6ea-11e9-9c02-de356cd90a46.png)
