### ISSUE TITLE
Strider (U) hanging in the loading screen after booting

### ISSUE THREAD

**Issue by literalmente-game** [JaCzekanski/Avocado#66]
**Game**: Strider (U). ID: SLUS-01142
**OS**: Windows 7
**Version**: 43d0631
**Hardware**:  i3 2100, GTX 1050 TI, 8GB RAM DDR3
**Behavior**: Avocado hangs in the loading screen shown below, right after booting
**Attachments**:
Screen where the game hangs on:
![unknown (1)](https://user-images.githubusercontent.com/24926584/72650212-8cca5200-395e-11ea-838c-43aff58d5ea0.png)
Log spam:
![unknown](https://user-images.githubusercontent.com/24926584/72650214-8cca5200-395e-11ea-965a-b2176aefa0f0.png)

**Comment by JaCzekanski** [comment]
Fixed
