### ISSUE TITLE
Tomba! (USA) SCUS-94236 - Broken rendering

### ISSUE THREAD

**Issue by tummyache123** [JaCzekanski/Avocado#83]
**Game**: Tomba! SCUS-94236

**Version**: d224545

**Hardware**: Ryzen 7 3700X, 2070 Super, 32GB RAM, Windows 10 2004 x64

**Behavior**: Certain graphics are broken/do not display properly. The peach plant in the beginning of the game does not render properly, and the fog is instead a black void.

**Attachments**:
  * **Screenshots/Videos**: 
![Tomba_SCUS-94236](https://user-images.githubusercontent.com/70869203/92341775-53c52600-f084-11ea-8a10-6922c1079d5f.PNG)

![Tomba_SCUS-94236_2](https://user-images.githubusercontent.com/70869203/92341861-a7d00a80-f084-11ea-8fcc-7e18f0d2ad09.PNG)

Expected behavior: https://youtu.be/pzhBSgq8Ep8?t=248

  * **Logs**:
[INFO] Using bios SCPH1001.BIN
[INFO] Loaded memory card 1 from card1.mcr
Loaded last state
Controller XInput Controller connected

PS-X Realtime Kernel Ver.2.5
Copyright 1993,1994 (C) Sony Computer Entertainment Inc.
KERNEL SETUP!

Configuration : EvCB    0x10            TCB     0x04
System restarted
System ROM Version 2.2 12/04/95 A
Copyright 1993,1994,1995 (C) Sony Computer Entertainment Inc.
ResetCallback: _96_remove ..
[GPU] GP0(0) nop: non-zero argument (0x07920c)
[GPU] GP0(0) nop: non-zero argument (0x07920c)
System Controller ROM Version 94/09/19 c0
SetGraphDebug:level:1,type:0 reverse:0

BOOTSTRAP LOADER Type C Ver 2.1   03-JUL-1994
Copyright 1993,1994 (C) Sony Computer Entertainment Inc.
setup file    : cdrom:SYSTEM.CNF;1
TCB     00000004
EVENT   00000010
STACK   80200000
BOOT =  cdrom:\SCUS_942.36;1
argument =
KERNEL SETUP!

Configuration : EvCB    0x10            TCB     0x04
boot file     : cdrom:\SCUS_942.36;1
EXEC:PC0(8006b58c)  T_ADDR(80010000)  T_SIZE(00088000)
boot address  : 8006b58c 80200000
Execute !

                S_ADDR(80200000)  S_SIZE()
[Timer1]: Synchronization enabled: 3
[GPU] GP0(0) nop: non-zero argument (0x090c54)

**Comment by JaCzekanski** [comment]
Looks like Tomba! uses undocumented GPU polygon commands and Avocado was not reading color for the first vertex for those polygons. Fixed.

![Screenshot 2020-09-08 at 00 23 48](https://user-images.githubusercontent.com/3662990/92418896-716cbb00-f16a-11ea-9ffe-71ea28cb1b25.png)
![Screenshot 2020-09-08 at 00 23 22](https://user-images.githubusercontent.com/3662990/92418897-729de800-f16a-11ea-82b6-3326eb0cb1cb.png)
