### ISSUE TITLE
Cannot install Android version

### ISSUE THREAD

**Issue by kevinalpian** [JaCzekanski/Avocado#89]
![Screenshot_20200914-034255550](https://user-images.githubusercontent.com/56602652/93028237-a54d5200-f63c-11ea-9336-f275a98f92a5.jpg)
**Game**: What game you're trying to play/test (including the game ID, listed as "Serial" here http://redump.org/discs/system/psx/)

**Version**: specify what build of Avocado you're using. (see Help->About)

**Hardware**: CPU, GPU, RAM, Operating system

**Behavior**: give details about what is happening with game/emulator 

**Attachments**:
  * **Screenshots/Videos**: (if possible (and when applicable), add a screenshot or video about the issue)
  * **Save state**: (use Backspace to rewind emulation few seconds before the issue happend and make quick save using F5, state can be found in data/state/GAME_ID_0.state)
  * **Logs**: (if available)

**Comment by birdybro** [comment]
Is this an accurate translation?

![image](https://user-images.githubusercontent.com/16388068/93028278-ff63fe00-f5cf-11ea-85ba-a33cc6d797b1.png)

If so I got the same result on a Google Pixel 3xl just now when testing with android build --> https://github.com/JaCzekanski/Avocado/commit/1d5645512c0ab94db8e6aedfc26ccfb7cb43383a

**Comment by JaCzekanski** [comment]
My fault - CI was building Debug version with only x86_64 ABI available. 
A fixed version should be available in a few minutes.

**Comment by JaCzekanski** [comment]
You can grab the latest version [here](https://avocado-builds.czekanski.info/#d6aeff3)

**Comment by kevinalpian** [comment]
![Screenshot_20200914-042034187](https://user-images.githubusercontent.com/56602652/93028955-bfd5fa00-f641-11ea-9abc-cfe058c69a56.jpg)
I'm confused about the controller.

**Comment by JaCzekanski** [comment]
There's no on-screen controller implemented right now - it's the exact same version as you have on PC.
You have to use Bluetooth/USB controller for now.

**Comment by kevinalpian** [comment]
doesn't work even when using the joystick, hope the next update there is a controller or joystick support

**Comment by birdybro** [comment]
What controller are you using? Have you mapped the controls in the options?

**Comment by kevinalpian** [comment]
yes I did the mapping, when the mapping was possible but didn't work in the game, I used the terios Bluetooth joystick and used Android as the jostick

**Comment by birdybro** [comment]
I will test any other controller when I get a chance, I have seen one other game that did not recognize inputs, and this game hasn't been tested yet according to the compatibility db. Which version are you using out of these --> http://redump.org/discs/quicksearch/metal-slug-x/  ? I'd like to recreate your steps somewhat, but with a different controller. Thanks.

**Comment by kevinalpian** [comment]
SLUS-01212

**Comment by birdybro** [comment]
Sorry for doing this late. I had a weirdly busy week at work and was just kinda scatter brained.

Yes, Metal Slug X does not register inputs as far as I can tell (using PS3 dualshock over USB on Windows 10, newest commit as of now). Might have to try some other controllers. If this is happening in Windows, I assume it's similar problem in Android, need to pair a controller to android still :P
