### ISSUE TITLE
Shaded lines rendered with wrong color [PDX-014]

### ISSUE THREAD

**Issue by spacepaw** [JaCzekanski/Avocado#95]
#### Informations

**Game**: pdx-014 (not a game, but intro)
**Version**: windows64-20201221-2fd5325
**Hardware**: AMD Ryzen 9 3900X, GeForce RTX 2080, 64GB, Windows 10
**BIOS**: SCPH1001

## Behavior 
The dots in the background should be white, but they are black in Avocado.

### Actual
![pdx-014-actual](https://user-images.githubusercontent.com/76810945/103410660-8f708800-4b6c-11eb-8194-472f83d3004a.png)

### Expected
![pdx-014-expected](https://user-images.githubusercontent.com/76810945/103410583-491b2900-4b6c-11eb-8e47-530e03e35bb2.png)

#### Attachments
You can download the PS-X EXE from the pouet demo scene website: http://www.pouet.net/prod.php?which=48782
You can also find a screenshot of the PS-X EXE on that same site.

**Comment by JaCzekanski** [comment]
Color in 0-length lines was interpolated incorrectly.
(Lines are used in this demo for white dots rendering)
